### ISSUE TITLE
mfoc via uart

### ISSUE THREAD

**Issue by correaraul** [nfc-tools/mfoc#17]
I have an Adafruit PN532 Breakout Board and an FTDI Friend.
I've installed the libnfc to use via uart and I can successfully use my NFC/RFID reader (nfc-list), but when I try to use the mfoc, it gives me a "No NFC device found" error.
What can I do?

**Comment by neomilium** [comment]
Issue tracker is not a forum.
Please use a better place to ask questions:

http://groups.google.com/group/nfc-tools

www.libnfc.org/community/
