### ISSUE TITLE
MFOC doesn't write into the output file and recovers no keys

### ISSUE THREAD

**Issue by aev1tas** [nfc-tools/mfoc#22]
I am running mfoc on Mac OS X, installed with Homebrew. 

ffff-MacBook-Pro:~ ffff$ mfoc -k ffffeeeedddd -O mycard.mfd
The custom key 0xffffeeeedddd has been added to the default keys
ISO/IEC 14443A (106 kbps) target:
    ATQA (SENS_RES): ff  ff  
* UID size: single
* bit frame anticollision supported
       UID (NFCID1): ff  ff  ff  ff  
      SAK (SEL_RES): ff  
* Compliant with ISO/IEC 14443-4
* Not compliant with ISO/IEC 18092
                ATS: ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  
* Max Frame Size accepted by PICC: 256 bytes
* Bit Rate Capability:
  * Same bitrate in both directions mandatory
* Frame Waiting Time: 77.33 ms
* Start-up Frame Guard Time: 1.208 ms
* Node Address not supported
* Card IDentifier not supported
* Historical bytes Tk: 44  49  20  30  32  56  
  * Proprietary format

Fingerprinting based on MIFARE type Identification Procedure:
* SmartMX with MIFARE 1K emulation
Other possible matches based on ATQA & SAK values:
* JCOP31 v2.3.1

Try to authenticate to all sectors with default keys...
Symbols: '.' no key found, '/' A key found, '\' B key found, 'x' both keys found
[Key: ffffeeeedddd] -> [xxxxxxxxxxxxxxxx]
[Key: ffffffffffff] -> [xxxxxxxxxxxxxxxx]
[Key: a0a1a2a3a4a5] -> [xxxxxxxxxxxxxxxx]
[Key: d3f7d3f7d3f7] -> [xxxxxxxxxxxxxxxx]
[Key: 000000000000] -> [xxxxxxxxxxxxxxxx]
[Key: b0b1b2b3b4b5] -> [xxxxxxxxxxxxxxxx]
[Key: 4d3a99c351dd] -> [xxxxxxxxxxxxxxxx]
[Key: 1a982c7e459a] -> [xxxxxxxxxxxxxxxx]
[Key: aabbccddeeff] -> [xxxxxxxxxxxxxxxx]
[Key: 714c5c886e97] -> [xxxxxxxxxxxxxxxx]
[Key: 587ee5f9350f] -> [xxxxxxxxxxxxxxxx]
[Key: a0478cc39091] -> [xxxxxxxxxxxxxxxx]
[Key: 533cb6c723f6] -> [xxxxxxxxxxxxxxxx]
[Key: 8fd0a4f256e9] -> [xxxxxxxxxxxxxxxx]

Sector 00 -  FOUND_KEY   [A]  Sector 00 -  FOUND_KEY   [B]  
Sector 01 -  FOUND_KEY   [A]  Sector 01 -  FOUND_KEY   [B]  
Sector 02 -  FOUND_KEY   [A]  Sector 02 -  FOUND_KEY   [B]  
Sector 03 -  FOUND_KEY   [A]  Sector 03 -  FOUND_KEY   [B]  
Sector 04 -  FOUND_KEY   [A]  Sector 04 -  FOUND_KEY   [B]  
Sector 05 -  FOUND_KEY   [A]  Sector 05 -  FOUND_KEY   [B]  
Sector 06 -  FOUND_KEY   [A]  Sector 06 -  FOUND_KEY   [B]  
Sector 07 -  FOUND_KEY   [A]  Sector 07 -  FOUND_KEY   [B]  
Sector 08 -  FOUND_KEY   [A]  Sector 08 -  FOUND_KEY   [B]  
Sector 09 -  FOUND_KEY   [A]  Sector 09 -  FOUND_KEY   [B]  
Sector 10 -  FOUND_KEY   [A]  Sector 10 -  FOUND_KEY   [B]  
Sector 11 -  FOUND_KEY   [A]  Sector 11 -  FOUND_KEY   [B]  
Sector 12 -  FOUND_KEY   [A]  Sector 12 -  FOUND_KEY   [B]  
Sector 13 -  FOUND_KEY   [A]  Sector 13 -  FOUND_KEY   [B]  
Sector 14 -  FOUND_KEY   [A]  Sector 14 -  FOUND_KEY   [B]  
Sector 15 -  FOUND_KEY   [A]  Sector 15 -  FOUND_KEY   [B]  

We have all sectors encrypted with the default keys..

Auth with all sectors succeeded, dumping keys to a file!
nfc_initiator_mifare_cmd: Success

And this is the output. I get that after about 5 seconds of touching the card. However the output file is empty.
I have manually installed mfoc and used this fix (http://www.george-smart.co.uk/wiki/NFC_Experiments). Here the output file got written, however it was mainly just 0000. 

What could be the problem?

**Comment by YeLincoln** [comment]
ATQA  should never be " ff ff " ,so I guess something wrong with your libnfc instead of mfoc.

**Comment by aev1tas** [comment]
That's fine, I changed it, it was a normal value beforehand. :-)

YeLincoln wrote:
