### ISSUE TITLE
New feature request

### ISSUE THREAD

**Issue by krusic22** [nfc-tools/mfoc#25]
I don't have a NFC reader. So I used the one on my Nexus 7 to make a dump. Now I want to get the key that is used on the card (to crack it). 
Can you add a way of using dump to crack it or is it impossible just because of the way it works?

**Comment by matthew5025** [comment]
Not possible.
The offline nested attack require the card to be present.

**Comment by hugoferreiraads** [comment]
sure, it required the card.

2015-09-08 9:09 GMT-03:00 matthew5025 <notifications@github.com>:

> Not possible.
> The offline nested attack require the card to be present.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nfc-tools/mfoc/issues/25#issuecomment-138534015>.
>



-- 
Hugo Ferreira

Estudante -  Análise e Desenvolvimento de Sistemas | ETEP Faculdades

**Comment by krusic22** [comment]
But could you use a rooted android device as a nfc reader or if you could
run this program on a rooted android device.

**Comment by hugoferreiraads** [comment]
Unfortunately not, you'll need a external nfc reader


2015-09-09 12:33 GMT-03:00 Kristjan Krušič <notifications@github.com>:

> But could you use a rooted android device as a nfc reader or if you could
> run this program on a rooted android device.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nfc-tools/mfoc/issues/25#issuecomment-138948556>.
>



-- 
Hugo Ferreira

Estudante -  Análise e Desenvolvimento de Sistemas | ETEP Faculdades

**Comment by koen-github** [comment]
Would it be possible to port MFOC to android using android's internal NFC system? So make use of all the NFC libraries provided by Google..

**Comment by matthew5025** [comment]
Not possible. Mfoc needs the ability to custom set parity nits, which cannot be done on android.
