### ISSUE TITLE
Response time significantly much higher in lastest version of MFOC?

### ISSUE THREAD

**Issue by amoeles** [nfc-tools/mfoc#30]
Here the time experiment with same commands on mfcuk and mfoc and the same tag&reader but diferent versions of nfc-tools.

**Results (min aprox):**

**MFOC 0.10.3**, libnfc 1.5.1  & mfcuk 0.3.3 > Time to obtain all keys: **15 min** (2min mfcuk and **10min mfoc with only one probe by sector**)

**MFOC 0.10.7**, libnfc 1.7,1 & mfcuk 0.3.8 > Time to obtain all keys: **60 min** (15min mfcuk and **45min mfoc with 20-45 probes by sector**)

_In two case i use these commands: "mfcuk -C -R 0:A -v 2" and "mfoc -k xxxxxxxxxxx -O keys.mfd -P 100"
Tag&reader: Mifare classic 1k tag, reader SCL3711._

**Why the lastest version of nfc-tools are more slow?**

**Comment by neomilium** [comment]
Internal changes in libnfc could affect mfoc performances. Feel free to contribute to improve it.
