### ISSUE TITLE
 MFOC -D output key is reversed .

### ISSUE THREAD

**Issue by sumanblack666** [nfc-tools/mfoc#38]
![image](https://user-images.githubusercontent.com/2647486/28376400-95a9208c-6cdc-11e7-988a-b00ffc9bc9ee.png)

actual key is 729c6c622f34

![image](https://user-images.githubusercontent.com/2647486/28376572-0ad8bc5a-6cdd-11e7-958e-5cb4f8b98930.png)

there's no error compiling MFOC.I compiled in Kali 2017.1 any idea why the output key when i used -D commandline is reversed .

**Comment by EmuAGR** [comment]
I can replicate this problem, I'm going to review the code.
