### ISSUE TITLE
Sector 1 no key

### ISSUE THREAD

**Issue by dimitrire** [nfc-tools/mfoc#63]
HI, I have a mifare card and the problem is that I can not read sector 1 with MCT on Android, how can I find the key? I also have the ACR122u reader, thank you for your help, Regards Dimitri

**Comment by dimitrire** [comment]
![screenshot_20190108-183802](https://user-images.githubusercontent.com/22459158/50852698-90f18600-1380-11e9-8a38-2cd1962aa78a.jpg)
 The details of the card

**Comment by 5trohm** [comment]
try mfoc or mfcuk with you arc122u

**Comment by wwin3286tw** [comment]
Get other sectors key first.
Did you use mfoc yet?
